from pathlib import Path
text = Path("temp-home.html").read_text(encoding="utf-16", errors="ignore")
btn_idx = text.find('button type="submit"')
form_idx = text.rfind('<form', 0, btn_idx)
close_idx = text.find('</form>', form_idx)
print('button idx', btn_idx)
print('form idx', form_idx)
print('close idx', close_idx)
print('snippet around form start:')
print(text[form_idx:form_idx+250])
print('snippet around button:')
print(text[btn_idx-250:btn_idx+250])
print('form closing snippet:')
print(text[close_idx-100:close_idx+80])
